### ISSUE TITLE
Redesign the replication engine

### ISSUE THREAD

**Issue by tahpot** [verida/storage-node#56]
## Current issues

The current [server side replication implementation](https://github.com/verida/VIPs/blob/develop/VIPs/vip-6.md) relies heavily on the CouchDB algorithm to select which replications need to occur. A replication record is created in CouchDB for every database and CouchDB then attempts to ensure all those replications occur as fast as possible.

Unfortunately, this CouchDB algorithm has no ability to detect when data has changed and prioritize replicating that data. As such, CouchDB attempts to replicate every single database even if it hasn't changed. This creates huge resource utilization (CPU and memory) that means the storage nodes are maxed out with only `100` users and `1000` databases. This is clearly not scalable.

## New architecture

A new design will be implemented that does not create any longstanding replication entries in CouchDB. Rather it will work as follows:

1. When a user opens a database the storage node will commence replicating that database to the other replicating nodes with a flag to expire the replication after 20 minutes
2. When a user obtains a new access key token the storage node (every 10 minutes) the protocol will ping the storage node which will extend the expiration to be another 20 minutes
3. The storage node will randomly select 1% of API requests to do a check to see if there are replication entries that have expired

This ensures databases are only replicated if they are being written to.

**Comment by nick-verida** [comment]
Is the intention to use CouchDB continuous replication or to continually schedule once-off replications (I assume CouchDB provides an API to cancel continuous replications?)

> The storage node will run a background process to kill replications that have expired

Can this be built into the storage-node app as opposed to another, separate app to manage?

**Comment by tahpot** [comment]
Yes, will be continuous and then cancelled.

Yes, will be built into the existing app. Will cheat and use a garbage collector strategy on % of API requests to trigger cleanup, instead of running a separate process.
