### ISSUE TITLE
Update readme file to remove obsolete links and references to testnet and centralized servers

### ISSUE THREAD

**Issue by ysam21** [verida/storage-node#75]
Update readme file to remove obsolete links and references to testnet and centralized servers.

Examples include:

  

> $env:DID_SERVER_URL="https://dids.testnet.verida.io:5001"

> Note: You may need to update .env to point to the appropriate Verida DID Server endpoint to use. By default it points to testnet, but you can point to a localhost instance for development purposes (http://localhost:5001/) -- note, there is no trailing /

> This server is running on the Verida Testnet and is accessible by any application built on the Verida network during the pre-launch phase.

> Testnet
> https://db.testnet.verida.tech/
> https://messages.testnet.verida.tech/

**Comment by tahpot** [comment]
Fixed

https://github.com/verida/storage-node/commit/c42971eb4ecb63b2acc6edab15bda7a02fda4bb5
