### ISSUE TITLE
Deploy tools

### ISSUE THREAD

**Issue by tahpot** [verida/storage-node#83]
We require scripts to help node operators easily get nodes up and running.

These scripts could exist in a `deploy-tools` folder in this repo, or a separate `storage-node-deploy-tools` repo. I'm not sure which is best?

We should use `pm2` for managing the running of the `storage-node` process.

I have specified `ubuntu` as the type of server to use on the assumption there is a consistent `ubuntu` image that can be used across AWS, GCP and Azure; but this assumption could be wrong?

## Scripts

- `generate-config.sh` - Generate `couchdb` config file and `storage-node` .env file. Prompt user for any necessary variables. Generate random variables as required.
- `ubuntu/init-machine.sh` - Install system requirements (git, couchdb, proxy server, nodejs, pm2 etc.) Open any ports. What else?
- `ubuntu/deploy-node.sh` - Deploy the `storage-node` server. Place generated config files into correct locations. Restart couchdb. Add `storage-node` to `pm2`. Start `storage-node`.
- `ubuntu/upgrade-node.sh` - Upgrade the `storage-node` code via git. Prompt for an optional version, default to `main` branch. Restart `storage-node` via `pm2`
- `ubuntu/deploy-ssl.sh` - Deploy letsencrypt SSL. Prompt for hostname.
- `ubuntu/renew-ssl.sh` - Renew letsencrypt SSL. Prompt for hostname.
- `ubuntu/install.sh` - Performan an installation from scratch, running the above scripts in the correct order to setup the machine and get the node running.

Are there any other scripts missing or that should be considered?

**Comment by tahpot** [comment]
See https://github.com/verida/storage-node-operators/blob/develop/setup/src/config-files.ts

**Comment by nick-verida** [comment]
Switched to https://github.com/verida/storage-node-operators/issues/ instead
